const SUBMISSION_STATUSES    = ['PENDING', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'PUBLISHED'];
const REGISTRATION_STATUSES  = ['REGISTERED', 'CONFIRMED', 'CANCELLED'];
const CERTIFICATE_STATUSES   = ['GENERATED', 'ISSUED', 'DOWNLOADED', 'REVOKED'];
const COMMITTEE_TEAMS        = ['ORGANIZING', 'SCIENTIFIC', 'REVIEW', 'HONORARY'];
const PARTICIPANT_TYPES      = ['STUDENT', 'RESEARCHER', 'PROFESSOR', 'ATTENDEE', 'INDUSTRY'];
const COMMITTEE_USER_ROLES   = ['ADMIN', 'REVIEWER', 'EDITOR'];
const CERTIFICATE_TYPES      = ['PARTICIPANT', 'SPEAKER'];

module.exports = {
  SUBMISSION_STATUSES,
  REGISTRATION_STATUSES,
  CERTIFICATE_STATUSES,
  COMMITTEE_TEAMS,
  PARTICIPANT_TYPES,
  COMMITTEE_USER_ROLES,
  CERTIFICATE_TYPES
};
